language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install: 
  - pip install -r requirements/development.txt
# command to run tests
script:
  - pep8 .
  - python fastube/manage.py test users posts
notifications:
  slack: jupiny:NrZkCoj1a9fQhGQaVHPHeAax
