language: python
python:
  - "3.4"
  - "3.5"
addons:
  postgresql: '9.3'
services:
  - redis-server
# command to install dependencies
install: 
  - pip install -r requirements/development.txt
  - pip install coveralls
before_script:
  - psql -c 'CREATE DATABASE fastube;' -U postgres
# command to run tests
script:
  - pep8 .
  - python fastube/manage.py test users posts
  - coverage run manage.py test
notifications:
  slack: jupiny:NrZkCoj1a9fQhGQaVHPHeAax
after_success: coveralls
